extends:
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/react'
rules:
  no-console: 1
  react/prop-types: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
plugins:
  - 'import'
  - 'jsx-a11y'
  - 'react'
  - 'react-hooks'
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  allowImportExportEverywhere: false
  ecmaFeatures:
    - jsx: true
env:
  es6: true
  browser: true
  node: true
settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      paths:
        - 'src'
  react:
    version: 'detect'
